// StreetBowl vendor data — Nigerian street food spots
window.SPOTS = [
  {
    id: 'mama-calabar-surulere',
    name: "Mama Calabar's Kitchen",
    tagline: "Edikang ikong that tastes like home.",
    type: 'Calabar / Soups',
    city: 'Lagos',
    area: 'Surulere',
    address: '14 Bode Thomas Street, Surulere, Lagos',
    rating: 4.8,
    reviews: 312,
    price: '₦500 - ₦3000',
    emoji: '🥘',
    image: 'Afang soup.jpg',
    color: 'from-palm/30 to-mustard/30',
    hours: 'Mon–Sat · 11:00am – 9:00pm',
    bestTime: 'Lunch rush, 1pm sharp',
    highlights: [
      { name: 'Edikang Ikong + Pounded Yam', price: '₦3,500', note: 'The whole reason you came.' },
      { name: 'Afang Soup + Eba',            price: '₦3,200', note: 'Periwinkles included, no shortcuts.' },
      { name: 'Goat Meat Pepper Soup',       price: '₦2,800', note: 'Order with cold malt. Trust.' },
      { name: 'Ekpang Nkukwo',               price: '₦2,500', note: 'Only on Saturdays. Get there early.' },
    ],
    reviewsList: [
      { name: 'Tomi A.', when: '3 days ago', rating: 5, text: "Mama scolded me for not finishing my eba. 10/10 will be scolded again." },
      { name: 'Ifeanyi O.', when: '1 week ago', rating: 5, text: "Best afang in Lagos. Don't argue with me." },
      { name: 'Adaeze K.', when: '2 weeks ago', rating: 4, text: "Worth the trek from Lekki. Bring cash, no POS." },
    ],
  },
  {
    id: 'suya-spot-wuse',
    name: 'Alhaji Musa Suya Spot',
    tagline: 'Wuse 2 institution. Open till the last stick is sold.',
    type: 'Suya / Grills',
    city: 'Abuja',
    area: 'Wuse 2',
    address: 'Opposite Sahad Stores, Aminu Kano Crescent, Wuse 2',
    rating: 4.9,
    reviews: 540,
    price: '₦600 - ₦2000',
    emoji: '🔥',
    image: 'suya.jpg',
    color: 'from-chili/30 to-ember/30',
    hours: 'Daily · 6:00pm – 2:00am',
    bestTime: 'After 10pm, when the smoke gets serious',
    highlights: [
      { name: 'Beef Suya (large)',  price: '₦2,000', note: 'Extra yaji on the side, always.' },
      { name: 'Ram Suya',           price: '₦3,500', note: 'Fridays & Saturdays only.' },
      { name: 'Chicken Kilishi',    price: '₦1,500', note: 'Crispy edges, smoky middle.' },
      { name: 'Tozo (hump)',        price: '₦4,000', note: 'For the real ones. Limited.' },
    ],
    reviewsList: [
      { name: 'Bola E.', when: '5 days ago', rating: 5, text: "Drove from Gwarinpa for this. Worth every drop of fuel." },
      { name: 'Hassan I.', when: '2 weeks ago', rating: 5, text: "Alhaji remembers your order after one visit. Legend." },
      { name: 'Chika M.', when: '1 month ago', rating: 4, text: "Pepper is not for the weak. Bring water." },
    ],
  },
  {
    id: 'iya-basira-jollof',
    name: 'Iya Basira Buka',
    tagline: 'Smoky party jollof, served on enamel plates.',
    type: 'Buka / Rice',
    city: 'Ibadan',
    area: 'Bodija',
    address: 'Off Awolowo Avenue, Bodija Market, Ibadan',
    rating: 4.7,
    reviews: 218,
    price: '₦1600 - ₦2500',
    emoji: '🍚',
    image: 'jollof rice.jpg',
    color: 'from-ember/30 to-chili/30',
    hours: 'Mon–Sat · 10:30am – 6:00pm',
    bestTime: 'By 12:30pm before the rice finishes',
    highlights: [
      { name: 'Party Jollof + Fried Plantain', price: '₦1,800', note: 'Crunchy bottom, smoky top.' },
      { name: 'Ofada Rice + Ayamase',          price: '₦2,500', note: 'Wraps in leaves. The way it should be.' },
      { name: 'Beans + Dodo',                   price: '₦1,200', note: 'Don\'t sleep on the beans.' },
      { name: 'Assorted Meat (per piece)',      price: '₦500',   note: 'Shaki, ponmo, liver — point and pay.' },
    ],
    reviewsList: [
      { name: 'Seun A.', when: '2 days ago', rating: 5, text: "I queued 25 minutes. I would queue again tomorrow." },
      { name: 'Funmi R.', when: '3 weeks ago', rating: 5, text: "The smokiness is unreal. How??" },
      { name: 'Tunde B.', when: '1 month ago', rating: 4, text: "Tight space, but the food makes up for it." },
    ],
  },
  {
    id: 'abacha-onitsha',
    name: 'Nne Chioma Abacha Joint',
    tagline: 'African salad with the right amount of ugba.',
    type: 'Igbo / Snacks',
    city: 'Onitsha',
    area: 'Upper Iweka',
    address: 'Beside Main Park, Upper Iweka Road, Onitsha',
    rating: 4.6,
    reviews: 174,
    price: '₦1000 - ₦2000',
    emoji: '🥗',
    image: 'abacha.jpg',
    color: 'from-palm/30 to-chili/20',
    hours: 'Daily · 12:00pm – 8:00pm',
    bestTime: 'Late afternoon with a chilled palm wine',
    highlights: [
      { name: 'Abacha + Fish',           price: '₦1,500', note: 'Fresh, oily, perfectly tangy.' },
      { name: 'Nkwobi (small bowl)',     price: '₦2,000', note: 'Cow foot game is strong.' },
      { name: 'Ugba & Stockfish',        price: '₦1,200', note: 'Snack while you wait.' },
      { name: 'Palm Wine (1 litre)',     price: '₦1,000', note: 'Tapped that morning.' },
    ],
    reviewsList: [
      { name: 'Obinna E.', when: '4 days ago', rating: 5, text: "Tastes exactly like village. I almost cried." },
      { name: 'Adanna I.', when: '2 weeks ago', rating: 4, text: "Service is slow but worth the wait." },
    ],
  },
  {
    id: 'akara-yaba',
    name: 'Iya Risi Akara Corner',
    tagline: 'Before-work akara with pap that hugs you.',
    type: 'Breakfast',
    city: 'Lagos',
    area: 'Yaba',
    address: 'Corner of Herbert Macaulay Way, Yaba, Lagos',
    rating: 4.5,
    reviews: 96,
    price: '₦600 - ₦2000',
    emoji: '🫘',
    image: 'pap and akara.jpg',
    color: 'from-mustard/30 to-ember/30',
    hours: 'Mon–Sat · 5:30am – 10:00am',
    bestTime: 'Catch her before 7:30am',
    highlights: [
      { name: 'Akara (5 pieces)',  price: '₦500',  note: 'Hot, golden, no oil dripping.' },
      { name: 'Pap (ogi)',         price: '₦300',  note: 'Smooth, no lumps, with milk.' },
      { name: 'Moi Moi',           price: '₦400',  note: 'Wrapped in real leaves.' },
      { name: 'Bread + Akara',     price: '₦600',  note: 'The student combo.' },
    ],
    reviewsList: [
      { name: 'Kelechi N.', when: '1 day ago', rating: 5, text: "Worth waking up at 6am. That's a sentence I never thought I'd write." },
      { name: 'Ronke A.', when: '2 weeks ago', rating: 4, text: "She closes early o, don't form Lagos time." },
    ],
  },
  {
    id: 'asun-ojota',
    name: 'Baba Tunde Asun Hub',
    tagline: 'Peppered goat meat that demands a cold drink.',
    type: 'Suya / Grills',
    city: 'Lagos',
    area: 'Ojota',
    address: 'Under the bridge, Ojota, Lagos',
    rating: 4.7,
    reviews: 281,
    price: '₦3000 - ₦5500',
    emoji: '🌶️',
    image: 'asun.jpg',
    color: 'from-chili/40 to-mustard/30',
    hours: 'Wed–Sun · 5:00pm – 1:00am',
    bestTime: 'Weekend nights — the vibe is the meal',
    highlights: [
      { name: 'Asun (small plate)',  price: '₦3,000', note: 'Goat meat, scotch bonnet, sliced onions.' },
      { name: 'Asun (large)',        price: '₦5,500', note: 'Sharing portion. Or not.' },
      { name: 'Isi Ewu',             price: '₦4,500', note: 'Goat head delicacy, done properly.' },
      { name: 'Grilled Catfish',     price: '₦4,000', note: 'Whole fish, butterflied, smoky.' },
    ],
    reviewsList: [
      { name: 'Damilola S.', when: '6 days ago', rating: 5, text: "The smoke alone deserves 5 stars." },
      { name: 'Emeka V.', when: '3 weeks ago', rating: 5, text: "Pepper made me question my life choices. Came back the next day." },
      { name: 'Yetunde O.', when: '1 month ago', rating: 4, text: "Parking is wahala, but the asun…" },
    ],
  },
  {
    id: 'shawarma-port-harcourt',
    name: 'Chief Shawarma Junction',
    tagline: 'PH-style shawarma, double sausage, extra sauce.',
    type: 'Snacks',
    city: 'Port Harcourt',
    area: 'GRA Phase 2',
    address: 'Aba Road, beside Mr. Bigg\'s, GRA Phase 2',
    rating: 4.4,
    reviews: 152,
    price: '₦1500 - ₦3500',
    emoji: '🌯',
    image: 'shawarma.jpg',
    color: 'from-ember/30 to-mustard/30',
    hours: 'Daily · 4:00pm – midnight',
    bestTime: 'Friday night, after the office crowd',
    highlights: [
      { name: 'Chicken Shawarma (XL)',  price: '₦2,800', note: 'The legendary one. Two sausages.' },
      { name: 'Beef Shawarma',          price: '₦2,500', note: 'Generous on the meat.' },
      { name: 'Special Combo + Drink',  price: '₦3,500', note: 'Comes with chips. Worth it.' },
      { name: 'Smoothie',                price: '₦1,500', note: 'Cools the pepper down.' },
    ],
    reviewsList: [
      { name: 'Goodluck A.', when: '2 days ago', rating: 5, text: "Best shawarma in PH, fight me." },
      { name: 'Mercy I.', when: '2 weeks ago', rating: 4, text: "Sauce game is unmatched." },
    ],
  },
  {
    id: 'tuwo-kano',
    name: 'Hajiya Aisha Tuwo Spot',
    tagline: 'Tuwo shinkafa with miyan kuka, the old way.',
    type: 'Northern',
    city: 'Kano',
    area: 'Sabon Gari',
    address: 'France Road, Sabon Gari, Kano',
    rating: 4.8,
    reviews: 203,
    price: '₦1000 - ₦2000',
    emoji: '🍲',
    image: 'tuwo.jpg',
    color: 'from-mustard/40 to-palm/30',
    hours: 'Mon–Sat · 11:00am – 4:00pm',
    bestTime: 'Lunchtime — she sells out by 3',
    highlights: [
      { name: 'Tuwo Shinkafa + Miyan Kuka', price: '₦1,500', note: 'Soft, fluffy, the kuka is dark and deep.' },
      { name: 'Tuwo + Miyan Taushe',         price: '₦1,500', note: 'Pumpkin soup, slightly sweet.' },
      { name: 'Dambun Nama',                 price: '₦2,500', note: 'Shredded spiced beef. Take some home.' },
      { name: 'Zobo (1 cup)',                price: '₦200',   note: 'Cold, gingery, perfect.' },
    ],
    reviewsList: [
      { name: 'Aminu K.', when: '5 days ago', rating: 5, text: "Reminds me of my grandmother's cooking. Pure soul." },
      { name: 'Fatima B.', when: '3 weeks ago', rating: 5, text: "Tuwo so soft it disappears in your mouth." },
    ],
  },
  {
    id: 'okpa-enugu',
    name: 'Mama Nkechi Okpa Stand',
    tagline: 'Enugu\'s favourite morning bambara nut pudding.',
    type: 'Breakfast',
    city: 'Enugu',
    area: 'New Haven',
    address: 'Chime Avenue, New Haven, Enugu',
    rating: 4.6,
    reviews: 88,
    price: '₦300 - ₦600',
    emoji: '🟡',
    image: 'okpa.jpg',
    color: 'from-mustard/30 to-cream',
    hours: 'Mon–Sat · 6:00am – 11:00am',
    bestTime: 'Morning, with hot pap',
    highlights: [
      { name: 'Okpa (wrap)',     price: '₦300', note: 'Steamed in leaves, peppery kick.' },
      { name: 'Okpa + Pap',      price: '₦600', note: 'The classic Enugu breakfast.' },
      { name: 'Bole + Fish',     price: '₦1,500', note: 'Roasted plantain with ground pepper.' },
    ],
    reviewsList: [
      { name: 'Chinedu O.', when: '1 week ago', rating: 5, text: "Takes me back to secondary school mornings." },
      { name: 'Ngozi A.', when: '1 month ago', rating: 4, text: "Get there early or no okpa for you." },
    ],
  },
];
